# Default values for chart.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1

image: ""

port: 80

text: "some text"

host: ""

enableCertificates: false
