apiVersion: landscaper.gardener.cloud/v1alpha1
kind: Blueprint

name: echo-server

reconciliation:
  enabled: true
  cron: '* * * 1'
  sideEffect: true

imports:
- name: cluster
  targetType: landscaper.gardener.cloud/kubernetes-cluster

- name: namespacedName
  schema:
    type: object
    properties:
      name:
        type: string
      namespace:
        type: string

- name: text
  schema:
    type: string

- name: host
  required: false
  schema:
    type: string

- name: enableCertificates
  required: false
  schema:
    type: boolean

deployExecutions:
- name: default
  type: GoTemplate
  template: |
    deployItems:
    - name: deploy
      type: landscaper.gardener.cloud/helm
      target:
        name: {{ .imports.cluster.metadata.name }}
        namespace: {{ .imports.cluster.metadata.namespace }}
      config:
        apiVersion: helm.deployer.landscaper.gardener.cloud/v1alpha1
        kind: ProviderConfiguration

        chart:
          {{- $resource := getResource .cd "name" "echo-server-chart" }}
          ref: {{ $resource.access.imageReference }}

        updateStrategy: patch

        values:
          {{- $resource := getResource .cd "name" "echo-server-image" }}
          image: {{ $resource.access.imageReference }}
          text: {{ .imports.text }}
          {{ if .imports.host }}
          host: {{ .imports.host }}
          {{ end }}
          {{ if .imports.host }}
          enableCertificates: {{ .imports.enableCertificates }}
          {{ end }}

        name: {{ .imports.namespacedName.name }}
        namespace: {{ .imports.namespacedName.namespace }}
